<!DOCTYPE html>
<html lang="zxx" class="js">
<head><meta charset="utf-8"><meta name="author" content="Softnio"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><meta name="description" content="<?php
if(isset($metaD) && !empty($metaD)) { 
   echo $metaD; 
} 
else { 
   echo "This is default"; 
} ?>">
<!-- Fav Icon --><link rel="shortcut icon" href="images/favicon.png">
<!-- Site Title  --><title><?php 
if(isset($title) && !empty($title)) { 
   echo $title; 
} 
else { 
   echo "Default title tag"; 
} ?></title><!-- Vendor Bundle CSS --><link rel="stylesheet" href="assets/css/vendor.bundle7500.css?ver=103"><!-- Custom styles for this template --><link rel="stylesheet" href="assets/css/style7500.css?ver=103" id="layoutstyle"><script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','../../www.google-analytics.com/analytics.js','ga');ga('create', 'UA-91615293-2', 'auto');ga('send', 'pageview');</script></head>
<body class="page-user"><div class="topbar-wrap"><div class="topbar is-sticky"><div class="container"><div class="d-flex justify-content-between align-items-center"><ul class="topbar-nav d-lg-none"><li class="topbar-nav-item relative"><a class="toggle-nav" href="#"><div class="toggle-icon"><span class="toggle-line"></span><span class="toggle-line"></span><span class="toggle-line"></span><span class="toggle-line"></span></div></a></li><!-- .topbar-nav-item --></ul><!-- .topbar-nav --><a class="topbar-logo" href="index.php"><img src="images/logo-light2x.png" srcset="images/logo-light2x.png 2x" alt="logo"></a><ul class="topbar-nav"><li class="topbar-nav-item relative"><span class="user-welcome d-none d-lg-inline-block">Welcome! Ayinde Samuel</span><a class="toggle-tigger user-thumb" href="#"><em class="ti ti-user"></em></a><div class="toggle-class dropdown-content dropdown-content-right dropdown-arrow-right user-dropdown"><div class="user-status"><h6 class="user-status-title">Token balance</h6><div class="user-status-balance">12,000,000 <small>TWZ</small></div></div><ul class="user-links"><li><a href="profile.php"><i class="ti ti-id-badge"></i>My Profile</a></li><li><a href="buy-token.php"><i class="ti ti-infinite"></i>Buy Token</a></li><li><a href="transactions.php"><i class="ti ti-eye"></i>My Transactions</a></li></ul><ul class="user-links bg-light"><li><a href="sign-in.html"><i class="ti ti-power-off"></i>Logout</a></li></ul></div></li><!-- .topbar-nav-item --></ul><!-- .topbar-nav --></div></div><!-- .container --></div><!-- .topbar --><div class="navbar"><div class="container"><div class="navbar-innr"><ul class="navbar-menu"><li><a href="index.php"><em class="ikon ikon-dashboard"></em> Home</a></li><li><a href="about.php"><em class="ikon ikon-coins"></em> About IGN</a></li><li><a href="howto.php"><em class="ikon ikon-distribution"></em> How To Buy & Sell</a></li><li><a href="faq.php"><em class="ikon ikon-transactions"></em> FAQ</a></li><li><a href="profile.html"><em class="ikon ikon-user"></em> News</a></li><li><a href="profile.html"><em class="ikon ikon-user"></em> Customers Feedback</a></li><li><a href="contact.php"><em class="ikon ikon-user"></em> Contact</a></li></ul><ul class="navbar-btns"><li><a href="kyc-application.php" class="btn btn-sm btn-outline btn-light"><em class="text-primary ti ti-files"></em><span>KYC Application</span></a></li><li class="d-none"><span class="badge badge-outline badge-success badge-lg"><em class="text-success ti ti-files mgr-1x"></em><span class="text-success">KYC Approved</span></span></li></ul></div><!-- .navbar-innr --></div><!-- .container --></div><!-- .navbar --></div><!-- .topbar-wrap -->